### PR TITLE
Add libmamba integration test

### PR DESCRIPTION
**Pull request by saraedum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
I am creating a bunch of PRs to see if we can catch breakage such as the one caused by #39 in the future with a simple integration test.

**Comment by saraedum** [comment]
Windows build fails with :tada: 

```
2024-01-04T02:45:19.1193633Z ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
```

**Comment by isuruf** [comment]
Isn't it better to use `test_downstreams` feature?

**Comment by saraedum** [comment]
> Isn't it better to use `test_downstreams` feature?

Yes, I saw that as well. Let me check if it works here. Initially I thought that mamba does not test functionality enough for this but probably the import of `libmambapy` already fails.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Pull request merged**
