### PR TITLE
Add run_exports

### PR DESCRIPTION
**Pull request by saraedum**
Since fmt is a shared library, we should tell every recipe that builds against it to require a compatible version at runtime.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by tdegeus** [comment]
This feature is new to me. Can you argue what this solves? I always thought that any package that builds against this library should just include the library (and optionally the version) in the dependencies. A second question is that if this is necessary, shouldn't it be done here https://github.com/conda-forge/conda-forge-pinning-feedstock ?

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
Sorry for the late reply.

> I always thought that any package that builds against this library should just include the library (and optionally the version) in the dependencies.

I believe that it used to be like that before this feature was available. This makes every package that has fmt in `host` have a compatible version in `run`.

> A second question is that if this is necessary, shouldn't it be done here conda-forge/conda-forge-pinning-feedstock ?

This is not the recommended way of doing things anymore: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/503#pullrequestreview-381724435

**Comment by tdegeus** [comment]
I finally sort of clarified the questions I was having. It seems that both this PR, as well as https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/503 should be merged to get proper pinning.

**Pull request merged**
