### PR TITLE
Restore compatibility with 10.1 ABI

### PR DESCRIPTION
**Pull request by saraedum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
We maybe want to wait to see what upstream thinks about this patch, see https://github.com/fmtlib/fmt/pull/3786

**Review by bdice — APPROVED** [review]
This seems fine — it’s probably more ideal than the run-export changes in #40 / #41. I’ll approve this PR, and let you work out the details with upstreaming the fix and/or choosing between this approach and tightening run-exports.

**Comment by h-vetinari** [comment]
> We maybe want to wait to see what upstream thinks about this patch, see [fmtlib/fmt#3786](https://github.com/fmtlib/fmt/pull/3786)

That's probably a good idea. We don't want to start shipping things that are our own invention, as that gets very tricky to maintain sanely. The patch looks pretty uncontroversial though, so I'm hopeful it'll will not run into insurmountable objections.

**Comment by saraedum** [comment]
Upstream is going to do a patch release with this patch applied. So let's go with this one and then mark build 0 as broken.

**Pull request merged**
