### PR TITLE
Fix ABI changes

### LINKED ISSUE #27: Undefined symbol in 8.1 for library built against 8.0
The symbol `_ZN3fmt2v86detail13error_handler8on_errorEPKc` was in 8.0 but is not in our 8.1 build anymore.

I am not sure why it is required but a [libintervalxt](https://github.com/conda-forge/intervalxt-feedstock/blob/master/recipe/meta.yaml#L37) library built against 8.0 is looking for that symbol; see [this error](https://github.com/flatsurf/flatsurf/runs/4698212878?check_suite_focus=true#step:6:554).

### PR DESCRIPTION
**Pull request by saraedum**
as in https://github.com/fmtlib/fmt/pull/2696

fixes #27

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by tdegeus** [comment]
Let's wait for the upstream fix to be merged. 
If it is I would still prefer a patch release upstream. Could you comment @vitaut ?

**Comment by saraedum** [comment]
> Let's wait for the upstream fix to be merged. If it is I would still prefer a patch release upstream.

Ok. But in that case we should mark 8.1.0 as broken. (Because it breaks stuff apparently.)

**Comment by vitaut** [comment]
There will be a patch release.

**Comment by saraedum** [comment]
I opened https://github.com/conda-forge/admin-requests/pull/367 to mark our 8.1.0 build as broken.

**Comment by saraedum** [comment]
Ok. We'll wait for the patch release then.

**Pull request closed without merging**
