### PR TITLE
Backport to fmt 10.1: Tighten run_export to max_pin='x.x'.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Backport of #40 to fmt 10.1.1. This should wait to merge until after #40 is approved and merged.

(I created a branch `fmt-10.1` and made it the target for this backport PR to avoid disrupting `main`. This is how I've seen other feedstocks handle backports in the past, please let me know if this is incorrect.)

### CODE REVIEW

**Comment by saraedum** [comment]
@bdice, I don't think this is the correct way to do this. Usually, we use a repodata patch to just update all the builds of 10.1 since we are not planning to maintain any newer 10.1 builds.

**Comment by saraedum** [comment]
Hm…or are the `run_exports` not part of the repodata and need to be patched in the actual packages? Then this would of course be the correct way to do this.

**Comment by saraedum** [comment]
Indeed, https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/224

Sorry for the noise then. run_exports cannot be patched.

**Comment by bdice** [comment]
Good question @saraedum. I think the actual package needs to be updated, which necessitates a backport.

I don't think run-exports are part of the repodata because it's not a solver constraint (repodata is just for the solver, afaik). A run-export is strictly build-time information needed by conda-build to generate the dependencies for a new package that depends on `fmt`, so it wouldn't really make sense to have that in the repodata.

**Review by saraedum — APPROVED** [review]

**Review by saraedum — COMMENTED** [review]
Let's hold off with this for a moment, see https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/628#issuecomment-1874862493

I think it's easier to mark 10.2.0 build 0 as broken and patch the missing symbol back in.

**Comment by h-vetinari** [comment]
This PR is now obsolete. Thanks for the quick handling (both for this PR and the more comprehensive fix)!

**Pull request closed without merging**
